/** batch5.mjs — B4: crops (66) + animals (16) = 82. CDN-bound per IMAGE_PROCESS.md §4. */
const KB=1024;
const crop=(k,part)=>({id:`CROP-${k.replace(/ /g,'_')}`,set:'objects-3d',
  subject:`a small harvest-ready portion of ${k} of the variety commonly grown in India — ${part} — arranged as one compact group, freshly picked, with one or two of its own green leaves included for identification`,
  outputs:[{path:`frontend/assets/crop/${k.replace(/ /g,'_')}.webp`,fmt:'webp',q:78,cap:20*KB}],density:[128,256]});
const animal=(k,breed)=>({id:`ANIMAL-${k.replace(/ /g,'_')}`,set:'objects-3d',
  subject:`${breed}, full body in strict side profile, standing squarely, healthy and well kept, no rope, no halter, no people, no shed`,
  outputs:[{path:`frontend/assets/animal/${k.replace(/ /g,'_')}.webp`,fmt:'webp',q:78,cap:24*KB}],density:[128,256]});

const CROPS={
 Tomato:'four ripe red tomatoes on the vine', Onion:'three unpeeled red onions with dry papery skin',
 Potato:'four unwashed brown potatoes with soil still on them', Brinjal:'three glossy purple brinjals with green calyx',
 Cauliflower:'one white cauliflower head with its green wrapper leaves', Cabbage:'one tight green cabbage head',
 Okra:'six tender green okra pods', 'Bitter Gourd':'three ridged green bitter gourds',
 Capsicum:'three glossy green capsicums', Cucumber:'three green cucumbers',
 'Bottle Gourd':'one long pale-green bottle gourd', Pumpkin:'one ripe orange pumpkin',
 Carrot:'five orange carrots with their green tops', Radish:'three white radishes with green tops',
 Spinach:'one bunch of fresh green spinach leaves', 'Green Chilli':'a handful of slender green chillies',
 Garlic:'three whole garlic bulbs with papery white skin', Ginger:'three knobbly fresh ginger rhizomes with soil on them',
 Coriander:'one bunch of fresh green coriander with roots', Fenugreek:'one bunch of fresh green fenugreek leaves',
 'Sweet Potato':'three unwashed reddish sweet potatoes', Peas:'six green pea pods, one split open showing peas',
 Mango:'two ripe Alphonso mangoes with a leafy twig', Banana:'one hand of ripe yellow bananas',
 Grapes:'one bunch of green table grapes', Pomegranate:'one whole pomegranate and one split open showing arils',
 Guava:'two whole guavas and one cut half', Papaya:'one ripe papaya and one cut half showing orange flesh and seeds',
 Watermelon:'one whole watermelon and one cut wedge showing red flesh', Muskmelon:'one whole muskmelon and one cut half',
 Orange:'three whole oranges with a leafy twig', Lemon:'four yellow-green lemons with a leafy twig',
 Apple:'three red apples with a leafy twig', Sapota:'four brown sapota fruits and one cut half',
 Pineapple:'one whole pineapple with its crown', Litchi:'a small cluster of red litchis on the twig',
 Coconut:'one whole brown coconut and one green tender coconut',
 Wheat:'three golden wheat ears on their stalks', Rice:'three golden rice panicles on their stalks',
 Maize:'two maize cobs, one with the husk peeled back showing yellow kernels',
 Bajra:'two compact pearl-millet spike heads on their stalks', Jowar:'two full sorghum grain panicles on short stalks',
 Barley:'three bearded barley ears on their stalks', Ragi:'two finger-millet heads with their finger-like spikes',
 'Tur Dal':'a cluster of pigeon-pea pods on the stem beside a small heap of split yellow dal',
 Gram:'a cluster of chickpea pods on the stem beside a small heap of whole brown chana',
 Moong:'a cluster of slender green-gram pods beside a small heap of whole green moong',
 Urad:'a cluster of black-gram pods beside a small heap of whole black urad',
 Masoor:'a cluster of lentil pods beside a small heap of orange split masoor',
 Soybean:'a cluster of fuzzy soybean pods on the stem beside a few pale beans',
 Groundnut:'a groundnut plant portion with pods still attached to the roots, soil clinging, one pod split open',
 Sunflower:'one mature sunflower head heavy with seeds, petals dried',
 Mustard:'a spray of mustard pods on the stem beside a small heap of tiny brown seeds',
 Sesame:'a stem of sesame capsules beside a small heap of pale sesame seeds',
 Castor:'one spiny castor seed cluster on the stem beside a few mottled castor beans',
 Cotton:'one open white cotton boll on its dried brown bur plus one unopened green boll',
 Sugarcane:'three cut sugarcane stalks with joints visible and one green leaf',
 Jute:'a bundle of retted golden jute fibre beside one green jute leaf',
 Turmeric:'three unwashed knobbly turmeric rhizome fingers with soil on them, one snapped to show the orange interior',
 'Red Chilli':'a handful of dried red chillies', Cumin:'a small heap of cumin seeds beside a sprig of the plant',
 'Coriander Seeds':'a small heap of round pale coriander seeds', Cardamom:'a small heap of green cardamom pods',
 'Black Pepper':'a small heap of black peppercorns beside one green pepper spike',
 Ajwain:'a small heap of ajwain seeds', Fennel:'a small heap of green fennel seeds beside a fennel flower head',
};
const ANIMALS={
 All:'a Gir cow, an Osmanabadi goat and an Indian country hen grouped together with the cow largest and centred',
 Cow:'a Gir cow with its distinctive domed forehead, long pendulous ears and red-and-white coat',
 Buffalo:'a Murrah buffalo with a jet-black coat and tightly curled horns',
 Goat:'an Osmanabadi goat with a black coat, standing upright',
 Bullock:'a single white Khillari bullock with long upswept horns and a muscular shoulder hump',
 Sheep:'a Deccani sheep with a coarse dark fleece',
 Poultry:'a single Indian country-fowl hen with mottled brown plumage and an upright tail',
 Horse:'a Marwari horse with its distinctive inward-curving ear tips',
 Camel:'a single-humped Indian dromedary camel',
 Pig:'a black Indian domestic pig',
 Duck:'a single Indian runner duck standing upright',
 Rabbit:'a single white domestic rabbit',
 Donkey:'a small grey Indian donkey',
 Dog:'an Indian pariah dog with a short tan coat and erect ears',
 Fish:'two freshwater rohu carp lying on a plain surface',
 Honeybee:'a single Indian honeybee on a small piece of honeycomb',
};
export const BATCH5=[...Object.entries(CROPS).map(([k,v])=>crop(k,v)),
                     ...Object.entries(ANIMALS).map(([k,v])=>animal(k,v))];
