/**
 * Tests for cache warming / preloading (services/cacheWarmer.service.js).
 *
 * Acceptance: hot keys are populated before the first user request post-deploy.
 * We verify the warmer calls getMarketPrices() for every hot combo (which is what
 * populates the in-process cache), tolerates failures, and skips cleanly when no
 * LLM key is configured. market.data.service and featureFlag.service are
 * module-mocked so warming runs without Gemini or a DB.
 */
import { jest } from '@jest/globals';

const getMarketPrices = jest.fn(async (commodity, state) => ({ crop: commodity, state, isFallback: false }));
jest.unstable_mockModule('../../../src/services/market.data.service.js', () => ({ getMarketPrices }));

const isEnabled = jest.fn(async () => true);
jest.unstable_mockModule('../../../src/services/featureFlag.service.js', () => ({ isEnabled }));

// ENV is read for GEMINI_API_KEY; mock it as a stable object whose property we
// mutate per-test (the consumer reads ENV.GEMINI_API_KEY off this same reference).
const fakeEnv = { GEMINI_API_KEY: 'test-key' };
jest.unstable_mockModule('../../../src/config/env.js', () => ({ ENV: fakeEnv }));

const { warmMarketCache, warmFeatureFlags, warmAllCaches } =
  await import('../../../src/services/cacheWarmer.service.js');

beforeEach(() => { getMarketPrices.mockClear(); isEnabled.mockClear(); fakeEnv.GEMINI_API_KEY = 'test-key'; });

describe('warmMarketCache', () => {
  test('warms every hot combo (one getMarketPrices call each) and reports them ok', async () => {
    const res = await warmMarketCache();
    expect(res.total).toBeGreaterThan(0);
    expect(getMarketPrices).toHaveBeenCalledTimes(res.total); // every hot key preloaded
    expect(res.ok).toBe(res.total);
    expect(res.fail).toBe(0);
  });

  test('does not depend on GEMINI_API_KEY — warming is not an LLM path', async () => {
    // This asserted `res.skipped === true` when GEMINI_API_KEY was blank, from
    // when mandi prices were generated by an LLM and warming an empty key was a
    // pointless paid call. That path is gone: market.data.service.js now serves
    // deterministic offline estimates ("NO AI / NO external LLM"), so the guard
    // was removed with the dependency and the assertion has failed ever since.
    //
    // Inverted rather than deleted, so it now guards the property that actually
    // matters — that warming the mandi cache never reintroduces a per-key LLM
    // call keyed on a provider credential.
    fakeEnv.GEMINI_API_KEY = '';
    const res = await warmMarketCache();
    expect(res.skipped).toBeUndefined();
    expect(getMarketPrices).toHaveBeenCalledTimes(res.total);
    expect(res.total).toBeGreaterThan(0);
  });

  test('counts fallback/failed results as misses, not warm', async () => {
    getMarketPrices.mockImplementation(async (c, s) => ({ crop: c, state: s, isFallback: true }));
    const res = await warmMarketCache();
    expect(res.ok).toBe(0);
    expect(res.fail).toBe(res.total);
  });

  test('a rejected warm call does not abort the rest of the batch', async () => {
    getMarketPrices
      .mockRejectedValueOnce(new Error('gemini down'))
      .mockResolvedValue({ isFallback: false });
    const res = await warmMarketCache();
    expect(getMarketPrices).toHaveBeenCalledTimes(res.total); // all attempted despite one throw
    expect(res.fail).toBeGreaterThanOrEqual(1);
    expect(res.ok).toBeGreaterThan(0);
  });
});

describe('warmAllCaches', () => {
  test('warms feature flags and market cache, never throws', async () => {
    await expect(warmAllCaches()).resolves.toBeUndefined();
    expect(isEnabled).toHaveBeenCalled();
    expect(getMarketPrices).toHaveBeenCalled();
  });

  test('warmFeatureFlags swallows errors', async () => {
    isEnabled.mockRejectedValueOnce(new Error('db down'));
    await expect(warmFeatureFlags()).resolves.toBeUndefined();
  });
});
